id: be2937ff72ce494aa80e3250d9b5038c
initial_creation_type: ocr
source_metadata:
  volumes:
    cf430a7598ec4e1bb722431d9fbdf829:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ཁྲོ་བོའི་རྒྱལ་པོ་འཕགས་པ་མི་གཡོ་བ་ལ་བསྟོད་པ།
      total_pages: 1044
      volume_number: 38
